# Generated by Django 4.2 on 2025-12-11 17:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('guest_capacity_min', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('guest_capacity_max', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.TextField(help_text='List of features separated by commas or new lines')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('included', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='packages.package')),
            ],
            options={
                'ordering': ['service_name'],
            },
        ),
    ]
